name: Robo Quantitativo Profissional

on:
  schedule:
    # ESTRATÉGIA 20K: Roda a cada 30 minutos (minutos 00 e 30)
    # Das 11h às 01h UTC (08h às 22h Horário de Brasília)
    - cron: '0,30 11-23,0 * * *'
  workflow_dispatch: # Botão para rodar manual quando quiser

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      # Versão v4 já suporta Node.js mais novos e resolve o alerta
      - name: Checkout do codigo
        uses: actions/checkout@v4

      # Versão v5 é a mais atual para o Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Atualizado para uma versão mais rápida do Python

      - name: Instalar Dependencias
        run: pip install requests pandas

      - name: Rodar o Predador Quantitativo
        run: python robo.py
