name: Bot Quantitativo Profissional

on:
  schedule:
    # Roda a cada 1 hora (no minuto 11 para fugir de atrasos no servidor)
    # Das 13h às 01h UTC (que equivale exatamente a 10:00 às 22:00 em Brasília)
    - cron: '11 13-23,0,1 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    # Dá permissão ao robô para gravar o ficheiro CSV de histórico no repositório
    permissions:
      contents: write

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Dependencias
        run: pip install requests pandas

      - name: Rodar o Predador Quantitativo
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        # Chama explicitamente o seu arquivo correto
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }} #
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }} # 
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }} # 
        run: python bot_quant.py

      # Salva o histórico de apostas (CSV) de volta no GitHub
      - name: Salvar Forward Testing (Commit CSV)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add historico_apostas.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "📈 Atualiza banco de dados de apostas" && git push)
